---
# Source: olm/templates/0000_50_olm_00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: olm
---
# Source: olm/templates/0000_50_olm_00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: operators
